# Generated by Django 4.2.11 on 2024-04-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_ja_app', '0003_alter_doctor_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='expert',
            field=models.CharField(choices=[('general doctor', 'دکتر عمومی'), ('cosmetic dermatologist', 'cosmetic dermatologist'), ('cardiologist', 'cardiologist'), ('endocrinologist', 'endocrinologist'), ('gynecologist', 'gynecologist'), ('internist', 'internist'), ('ophthalmologist', 'ophthalmologist'), ('otolaryngologies', 'otolaryngologies'), ('plastic surgeon', 'plastic surgeon'), ('pediatrician', 'pediatrician')], max_length=120),
        ),
    ]
