# Generated by Django 4.2.11 on 2024-04-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_ja_app', '0006_alter_doctor_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_c',
            name='email',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
