# Generated by Django 4.2.11 on 2024-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_ja_app', '0007_doctor_c_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_c',
            name='email',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
