# Generated by Django 4.2.11 on 2024-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_ja_app', '0009_doctor_c_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hour',
            name='day',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hour',
        ),
        migrations.AddField(
            model_name='reservation',
            name='From',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='to',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='day',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Hour',
        ),
    ]
