# Generated by Django 4.2.11 on 2024-05-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_ja_app', '0012_alter_doctor_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
